use_frameworks!

#database
pod 'RealmSwift'

#frp
pod 'RxSwift', '~> 2.0.0-beta'
pod 'RxCocoa', '~> 2.0.0-beta'

#tab strips
pod 'XLPagerTabStrip', '~> 1.0'
pod 'KHTabPagerViewController', '~> 0.1.0'

#async tasks
pod 'TaskQueue'

#animation lib - re-include with version 0.7.1
#pod 'EasyAnimation'

#image cache
pod 'HanekeSwift'

#ui themes
pod 'MAThemeKit'

#colors
pod 'DynamicColor'

#pod credits
pod 'VTAcknowledgementsViewController'

#pod modal alert
pod 'SwiftSpinner'

#pod status bar message
pod 'CWStatusBarNotification'

#github repo JSImagePickerController
pod 'JSImagePickerController', git: 'https://github.com/icanzilb/JSImagePickerController.git', :tag => '0.6.1'

#pod net availability
pod 'Reachability'

#font awesome
pod 'Font-Awesome-Swift'

#copy the acknowledgements file when installing news pods
post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-acknowledgements.plist', 'Pods-acknowledgements.plist', :remove_destination => true)
end