use_frameworks!

#just because
pod 'EasyAnimation'

pod 'RxSwift'
pod 'RxCocoa'

pod 'RxViewModel', :git => "https://github.com/icanzilb/RxViewModel"

pod 'RxDataSources'
pod 'RxGesture'

pod 'RealmSwift'

pod 'MAThemeKit'
pod 'DynamicColor'

pod 'VTAcknowledgementsViewController'

pod 'CWStatusBarNotification'

pod 'Reachability'
pod 'Pager', :git => "https://github.com/lucoceano/Pager"
pod 'KHTabPagerViewController'
pod 'XLPagerTabStrip'

pod 'Then'
pod 'AFDateHelper'

pod 'MMMarkdown'

pod 'Moya/RxSwift'
pod 'SwiftyJSON'

pod 'RelativeFormatter'
pod 'Kingfisher'

pod 'Curry'

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-acknowledgements.plist', 'Pods-acknowledgements.plist', :remove_destination => true)
end
